name: Build, Test and Deploy Educable App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Build Docker Image
        run: docker build -t dmim .

      - name: Tag Docker Image
        run: docker tag dmim:latest docker.io/valens200/dmim:latest

      - name: Docker Login and Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io
          docker push docker.io/valens200/dmim:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create .ssh Directory
        run: mkdir -p $HOME/.ssh

      - name: Create known_hosts File
        run: touch $HOME/.ssh/known_hosts

      - name: Remove Old Host Key
        run: ssh-keygen -R ${{ secrets.DEPLOY_HOST }}

      - name: Add and Display Updated Host Key
        run: |
          HOST_KEY=$(ssh-keyscan -t rsa 10.10.82.249)
          echo "$HOST_KEY"
          echo "$HOST_KEY" >> $HOME/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          fingerprint: ${{ secrets.DEPLOY_FINGERPRINT }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io
            sudo docker pull docker.io/valens200/dmim
            sudo docker stop dmim || true
            sudo docker rm dmim || true
            sudo docker run -d --name dmim -p 3000:3000 -v /educable-dir/images/test:/opt/uploads/educapp-backend/images docker.io/valens200/dmim
