name: Prod Deploy to SSH Server

on:
  push:
    branches:
      - main
    paths-ignore: ['.vscode/**']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Create environment variables
        run: |
          chmod +x scripts/create_test_env.sh
          ./scripts/create_test_env.sh

      - name: Build Nest app
        run: npm run build

      - name: Upload .next folder to SSH server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: mis-prod-build.tar.gz
          target: ~/nextjs-builds

      - name: Deploy and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/actions-runner/_work/dmim_app/DMIM_backend_service
            chmod +x scripts/create_test_env.sh
            ./scripts/create_prod_env.sh
            git stash
            git pull origin main
            npm i
            pm2 restart main.ts
