name: production-deploy
on:
  push:
    branches: ["main"]
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Connect to Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/actions-runner/_work/dmim_app/DMIM_backend_service
            chmod +x scripts/create_test_env.sh
            ./scripts/create_prod_env.sh
            git stash
            git pull origin main
            npm i
            pm2 restart backend_test
